{% set version = "0.5.1" %}

package:
  name: python-snappy
  version: "{{ version }}"

source:
  fn: python-snappy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-snappy/python-snappy-{{ version }}.tar.gz
  md5: 0c06bbed70a8390b55a60f5ee79a27d2

build:
    number: 0
    skip: True  # [win]

requirements:
  build:
    - toolchain
    - python
    - snappy
    - cmake
  run:
    - python
    - snappy

test:
  imports:
     - snappy

about:
  home: http://github.com/andrix/python-snappy
  license: BSD 3-clause
  summary: 'Python library for the snappy compression library from Google'


extra:
  recipe-maintainers:
    - mariusvniekerk